[package]
name = "shared"
version = "0.1.0"
edition.workspace = true
publish = false

[lints]
workspace = true

[lib]
name = "shared"
path = "src/lib.rs"

[dependencies]
thiserror = { workspace = true }
