[package]
name = "entity"
version = "0.1.0"
edition.workspace = true
publish = false

[lints]
workspace = true

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
sea-orm = { workspace = true, features = ["macros"] }
serde = { workspace = true, features = ["derive"] }
