[package]
name = "library"
version = "0.1.0"
edition.workspace = true
publish = false

[lints]
workspace = true

[lib]
name = "library"
path = "src/lib.rs"

[dependencies]
shared = { path = "../shared" }
entity = { path = "../../entity" }
async-graphql = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
sea-orm = { workspace = true, features = [
  "sqlx-sqlite",
  "runtime-tokio-rustls",
  "macros",
] }
