[package]
name = "library"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[lib]
name = "library"
path = "src/lib.rs"

[dependencies]
entity = { path = "../../entity" }
async-graphql = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
sea-orm = { workspace = true, features = [
  "sqlx-sqlite",
  "runtime-tokio-rustls",
  "macros",
] }
