name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "src/**"
      - "src-tauri/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/**"
      - "biome.jsonc"
      - "tsconfig.json"

jobs:
  frontend:
    name: Frontend (Biome & TypeScript)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Biome lint
        run: pnpm lint

      - name: Run TypeScript type check
        run: pnpm typecheck

  rust:
    name: Rust (Tauri Backend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Run cargo check
        working-directory: src-tauri
        run: cargo check --all-targets

      - name: Run cargo clippy
        working-directory: src-tauri
        run: cargo clippy --all-targets -- -D warnings

      - name: Run cargo fmt check
        working-directory: src-tauri
        run: cargo fmt --check
